### ISSUE TITLE
Dispenser spikes deal insane knockback, Spike shooting delay/intervals

### ISSUE THREAD

**Issue by DylanGK** [Mrbysco/ModJNam-Mod#4]
So when a Spike hits a mob, it knocks them back quite far, which is thought was somewhat odd.

Also, there seems to be an internal delay between Spikes now (unaffected by how quickly the redstone pulses), which wasn't there in v1.0 if I'm correct. Is this intentional?

**Comment by Mrbysco** [comment]
Oh... that. Due to having to add attack damage to the spikes from the Dispenser. I had to try and put a timer on it to stop abuse. As if with a quick redstone clock you could make an impenetrable wall.

I'll tweak this in the future.

**Comment by Mrbysco** [comment]
Also sorry for responding so late. I somehow didn't get a notification for this issue

**Comment by DylanGK** [comment]
Ah no problem! Nothing you could do about that.

I'd suggest to lower the timer to, say, .5 seconds or something, as they only do 1 damage after all, but perhaps that's still too strong.

**Comment by Mrbysco** [comment]
Originally I had them be 0 damage but 2 knockback. But apparently 0 damage makes it bounce off of players which is why the issue of "Spikes do nothing"  existed
