### ISSUE TITLE
[Bug]: 1.16.5 Crash while loading with FashWorkbench

### ISSUE THREAD

**Issue by abundzu** [Mrbysco/ModJNam-Mod#6]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.23

### Mod version

1.3.6

### Java version

1.8.0_311

### Issue Description

Crashes while loading with both mods present. FastWorkbench is version 4.6.1.

Error given : 
The Cactus Mod (cacutsmod) had failed to load correctly
java.lang.NoClassDefFoundError: shadows/fastbench/gui/ContainerFastBench

### Additional Information

https://pastebin.com/YRJtYYA2

**Comment by Mrbysco** [comment]
Fixed in https://github.com/Mrbysco/ModJNam-Mod/commit/4cc997e5a135c3cfd9b203739a0ec2f9d044666a
Will be up on Curse soon
